version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=option123
    ports:
    - "5434:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
